BZM_API_BASE_URL: str = "https://a.blazemeter.com/api/v4"
VS_API_BASE_URL: str = "https://mock.blazemeter.com/api/v1"
BZM_BASE_URL: str = "https://a.blazemeter.com/"
TOOLS_PREFIX: str = "blazemeter"
VS_TOOLS_PREFIX: str = "virtual_services"

USER_ENDPOINT: str = "/user"
ACCOUNTS_ENDPOINT: str = "/accounts"
PROJECTS_ENDPOINT: str = "/projects"
WORKSPACES_ENDPOINT: str = "/workspaces"
TESTS_ENDPOINT: str = "/tests"
EXECUTIONS_ENDPOINT: str = "/masters"

VS_SERVICES_ENDPOINT: str = "services"
VS_TRANSACTIONS_ENDPOINT: str = "transactions"
VS_LOCATIONS_ENDPOINT: str = "locations"
VS_ENDPOINT: str = "service-mocks"
VS_TEMPLATE_ENDPOINT: str = "service-mock-templates"
VS_TRACKINGS_ENDPOINT: str = "trackings"
VS_SANDBOX_ENDPOINT: str = "sandbox"
VS_ACTIONS_ENDPOINT: str = "actions"
VS_ASSETS_ENDPOINT: str = "assets"
VS_CONFIGURATIONS_ENDPOINT: str = "service-mock-configurations"
VS_RECORDINGS_ENDPOINT: str = "recordings"
VS_TESTDATA_ENDPOINT: str = "testdata"
VS_BLUEPRINTS_ENDPOINT: str = "/blueprints"
VS_VALIDATIONS_ENDPOINT: str = "/system/validations/handlebars"
VS_CONVERT_ENDPOINT: str = "/system/validations/handlebars/convert"

TDM_API_BASE_URL: str = "https://ar.blazemeter.com/api/v1"
TDM_PACKAGES_ENDPOINT: str = "packages"
TDM_ASSETS_ENDPOINT: str = "assets"
